### ISSUE TITLE
Look at Laura's align technique

### ISSUE THREAD

**Issue by dlobser** [objectnormal/maevr#5]
experience/VRControlsExp.js Laura added some commented lines
experience/cameraUtil.js - align function gets called in maevr.js staticbegin()

It seems like her tricks are working but it could be integrated better

**Comment by scottgarner** [comment]
`staticbegin()` is not the proper place for this. First, I'd prefer nobody touched `maevr.js` but me. Second, that function is called when the audio starts to load, not when it starts to play. Third, it doesn't get called at all in event mode.

Like I mentioned in an email, the proper place for something like this is in `maevr.experience.js` in the `play()` function, which gets called in both static mode and event mode when the actual song timer starts.

As for the VRControls, it's usually a bad idea to mess with third-party libraries directly because it severely hampers the ability to update to new versions. In this case, the object you pass doesn't have to be a camera. I think rather than touching the script at all or bothering to extend it, I might just pass it an empty object, which I'd always know maintained the VR orientation. After the update, I'd take that reference object's orientation, alter it based on my alignment and then apply that to the camera. Maybe the camera could be a child of that object, or the alignment node could be a child of it and the camera a child of that. There are many options that don't require messing with vendor code.

As for the effectiveness of this approach, what if you're looking down or up or somewhere crazy when the start happens? Especially if you've just pressed a button and your phone is facing down?

Is the overall goal here to try to make sure that the experience is ahead of the user? What isn't happening by default that should be?

**Comment by scottgarner** [comment]
Figured out how to do this in one line.

```
  play: function() {
    console.log("MAEVR.Experience: play");
    MAEVR.vrControls.resetSensor();

    //MAEVR.Experience.Util.Align(MAEVR.camera,MAEVR.vrControls);
  },
```

The VR controls already had a reset function. No need to fuss with anything. This means that wherever you're facing when the music/event starts will be your front, though that should only effect yaw, not roll or pitch, which I think is what you are wanting.

No matter what we have the problem of somebody looking somewhere crazy. We could recenter on cardboard button press, which seems pretty normal.
